---
functional:
  - На сайте есть возможность зарегистрироваться
  - На сайте есть возможность авторизоваться
  - На сайте можно провести бой будучи не авторизованным пользователем 
  - На сайте можно создать игру выбрав любого пользователя, бота, или друга в качестве противника
  - На сайте при создании игры можно выбрать сложность, время, задачу
  - На сайте во время игры пользователь может (решить задачу, сбросить свое решение, сдаться, поменять язык программирования, написать в чат)  
  - На сайте другие пользователи могут следить за ходом игры
  - Можно посмотреть записи о завершенном бое
  - В лобби на сайте есть чат, в котором могут общаться зарегистрированные пользователи
  - Пользователь может создать турнир
  - Пользователь может следить за другими турнирами
  - Пользователь может присоединится к любому турниру и выйти из него
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - При создании игры можно указать теги
  - В игре во время решения задачи можно менять тему консоли (со светлой на темную и наоборот)
  - В настройках игры можно выбрать себе имя пользователя, "оружие", клан, настроить звук
  - На сайте можно посмотреть полный рейтинг игроков
  - На сайте можно создать задачу и свой собственный пакет задач, посмотреть задачи созданные другими пользователями
  - На сайте можно посмотреть информацию о любом игроке
  - В лобби можно вызвать на бой одного из представленных ботов
  - На сайте можно перейти на сайт Hexlet
  - На сайте можно перейти на телеграм канал Codebattle
