---
functional:
  - На сайте есть возможность зарегистрироваться
  - На сайте есть возможность авторизоваться
  - На сайте можно провести бой будучи не авторизованным пользователем 
  - В бою игроки видят два редактора. Слева - свой редактор, справа - соперника.
  - В бою наверху находится время игры и ниже - задание, справа чат
  - В бою каждый игрок видит код своего соперника в режиме он-лайн
  - В бою каждый игрок имеет кнопку "Run" для проверки своего решения.
  - В бою если вдруг один из игроков вылетел из игры, второй может продолжать играть. Первый в любой момент игры, пока она не закончена, может переподключиться в игру
  - Бой длится пока не истечет время, либо пока не выявится победитель
  - На сайте можно создать игру выбрав любого пользователя, бота, или друга в качестве противника
  - На сайте любой игрок может принять приглашение на бой
  - На сайте при создании игры можно выбрать сложность, время, задачу
  - На сайте во время игры пользователь может (решить задачу, сбросить свое решение, сдаться, поменять язык программирования, написать в чат)  
  - Когда один из игроков находит верное решение, обоим игрокам высвечивается модальное окно, где написано, кто является победителем этой игры
  - Игрок победитель может выйти из игры. Кнопка "Run" у него более неактивна, но он может остаться и посмотреть ещё раз на свой код.
  - Если игрок проиграл он может выйти, а может доиграть до конца
  - На сайте другие пользователи могут следить за ходом игры
  - Можно посмотреть записи о завершенном бое
  - В лобби на сайте есть чат, в котором могут общаться зарегистрированные пользователи
  - Пользователь может создать турнир
  - Пользователь может следить за другими турнирами
  - Пользователь может присоединится к любому турниру и выйти из него
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - При создании игры можно указать теги
  - В игре во время решения задачи можно менять тему консоли (со светлой на темную и наоборот)
  - В настройках игры можно выбрать себе имя пользователя, "оружие", клан, настроить звук
  - На сайте можно посмотреть полный рейтинг игроков
  - На сайте можно создать задачу и свой собственный пакет задач, посмотреть задачи созданные другими пользователями
  - На сайте можно посмотреть информацию о любом игроке
  - В лобби можно вызвать на бой одного из представленных ботов
  - На сайте можно перейти на сайт Hexlet
  - На сайте можно перейти на телеграм канал Codebattle
  - В бою шкала со временем меняет свой цвет в зависимости от того сколько времени осталось
